use CDI2;

select * from CUSTOMERS;

CREATE TABLE CUSTOMERS (
    CUST_ID INT,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    POSTALCODE VARCHAR(20),
    COUNTRY VARCHAR(50),
    PHONE VARCHAR(20),
    LAST_ORDER_DATE DATE,
    STATUS VARCHAR(20),
    TIER INT NULL,
    MODIFIED_DATE DATE
);


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/customer.txt'
INTO TABLE CUSTOMERS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS
(CUST_ID, NAME, ADDRESS, CITY, STATE, POSTALCODE, COUNTRY, PHONE, LAST_ORDER_DATE, STATUS, @TIER, MODIFIED_DATE)
SET TIER = NULLIF(@TIER, '');

CREATE TABLE dealerships (
    DEALERSHIP_ID INT,
    DEALERSHIP_MANAGER_ID INT,
    DEALERSHIP_DESC VARCHAR(255),
    DEALERSHIP_LOCATION VARCHAR(255),
    DEALERSHIP_STATE VARCHAR(255),
    DEALERSHIP_REGION VARCHAR(255),
    DEALERSHIP_COUNTRY VARCHAR(255)
);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/dealership.txt'
INTO TABLE dealerships
FIELDS TERMINATED BY ','
IGNORE 1 ROWS ;

CREATE TABLE employees (
    EMP_ID INT,
    EMP_FIRST_NAME VARCHAR(255),
    EMP_LAST_NAME VARCHAR(255),
    REGION_ID INT,
    Q1 DECIMAL(18, 4),
    Q2 DECIMAL(18, 4),
    Q3 DECIMAL(18, 4),
    Q4 DECIMAL(18, 4)
);
CREATE TABLE orders (
    ORDERID INT,
    QUANTITY INT,
    CUSTOMERID INT,
    SHIPMENTTRACKINGNO VARCHAR(255),
    ORDERSTATUS VARCHAR(255),
    PRODUCTDESCRIPTION VARCHAR(255),
    OUTLETID INT,
    PRODUCTID INT
);

CREATE TABLE accounts (
    ID INT,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
    PARENTID INT,
    BILLINGSTREET VARCHAR(255),
    BILLINGCITY VARCHAR(255),
    BILLINGSTATE VARCHAR(255),
    BILLINGPOSTALCODE VARCHAR(20),
    BILLINGCOUNTRY VARCHAR(255),
    SHIPPINGSTREET VARCHAR(255),
    SHIPPINGCITY VARCHAR(255),
    SHIPPINGSTATE VARCHAR(255),
    SHIPPINGPOSTALCODE VARCHAR(20),
    SHIPPINGCOUNTRY VARCHAR(255),
    PHONE VARCHAR(20),
    WEBSITE VARCHAR(255),
    INDUSTRY VARCHAR(255),
    NUMBEROFEMPLOYEES INT,
    DESCRIPTION TEXT,
    CREATEDDATE DATETIME,
    CREATEDBYID INT,
    LASTMODIFIEDDATE DATETIME,
    LASTMODIFIEDBYID INT,
    LASTACTIVITYDATE DATETIME,
    ANNUALREVENUE DECIMAL(18, 2)
);
ALTER TABLE accounts
MODIFY COLUMN ID VARCHAR(255);

CREATE TABLE supermarket_contacts (
    CUST_ID INT,
    COMPANY VARCHAR(255),
    ADDR1 VARCHAR(255),
    ADDR2 VARCHAR(255),
    ADDR3 VARCHAR(255),
    ADDR4 VARCHAR(255),
    COUNTRY VARCHAR(255),
    NAMEPREFIX VARCHAR(10),
    FIRSTNAME VARCHAR(255),
    SURNAME VARCHAR(255),
    TITLE VARCHAR(255),
    EMAIL VARCHAR(255)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/employee_sales.txt'
INTO TABLE EMPLOYEES
FIELDS TERMINATED BY ','
IGNORE 1 ROWS
(EMP_ID, EMP_FIRST_NAME, EMP_LAST_NAME, REGION_ID, Q1, Q2, Q3, Q4);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/orders.txt'
INTO TABLE ORDERS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS
(ORDERID, QUANTITY, CUSTOMERID, SHIPMENTTRACKINGNO, ORDERSTATUS, PRODUCTDESCRIPTION, OUTLETID, PRODUCTID);

use cdi2;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/SF_ACCOUNT.csv'
INTO TABLE accounts
FIELDS TERMINATED BY ','
IGNORE 1 ROWS
(ID, NAME, TYPE, PARENTID, BILLINGSTREET, BILLINGCITY, BILLINGSTATE, BILLINGPOSTALCODE, BILLINGCOUNTRY, SHIPPINGSTREET, SHIPPINGCITY, SHIPPINGSTATE, SHIPPINGPOSTALCODE, SHIPPINGCOUNTRY, PHONE, WEBSITE, INDUSTRY, @NUMBEROFEMPLOYEES, DESCRIPTION, @CREATEDDATE, CREATEDBYID, @LASTMODIFIEDDATE, LASTMODIFIEDBYID, @LASTACTIVITYDATE, @ANNUALREVENUE)
SET NUMBEROFEMPLOYEES = NULLIF(@NUMBEROFEMPLOYEES, ''),
CREATEDDATE = STR_TO_DATE(@CREATEDDATE, '%m/%d/%Y'),
LASTMODIFIEDDATE = STR_TO_DATE(@LASTMODIFIEDDATE, '%m/%d/%Y'),
LASTACTIVITYDATE = NULLIF(@LASTACTIVITYDATE, ''),
ANNUALREVENUE = NULLIF(@ANNUALREVENUE, '');








ALTER TABLE accounts
MODIFY COLUMN NAME VARCHAR(255),
MODIFY COLUMN TYPE VARCHAR(255),
MODIFY COLUMN PARENTID VARCHAR(255),
MODIFY COLUMN BILLINGSTREET VARCHAR(255),
MODIFY COLUMN BILLINGCITY VARCHAR(255),
MODIFY COLUMN BILLINGSTATE VARCHAR(255),
MODIFY COLUMN BILLINGPOSTALCODE VARCHAR(20),
MODIFY COLUMN BILLINGCOUNTRY VARCHAR(255),
MODIFY COLUMN SHIPPINGSTREET VARCHAR(255),
MODIFY COLUMN SHIPPINGCITY VARCHAR(255),
MODIFY COLUMN SHIPPINGSTATE VARCHAR(255),
MODIFY COLUMN SHIPPINGPOSTALCODE VARCHAR(20),
MODIFY COLUMN SHIPPINGCOUNTRY VARCHAR(255),
MODIFY COLUMN PHONE VARCHAR(20),
MODIFY COLUMN WEBSITE VARCHAR(255),
MODIFY COLUMN INDUSTRY VARCHAR(255),
MODIFY COLUMN NUMBEROFEMPLOYEES INT,
MODIFY COLUMN DESCRIPTION TEXT,
MODIFY COLUMN CREATEDDATE DATE,
MODIFY COLUMN CREATEDBYID VARCHAR(255),
MODIFY COLUMN LASTMODIFIEDDATE DATE,
MODIFY COLUMN LASTMODIFIEDBYID VARCHAR(255),
MODIFY COLUMN LASTACTIVITYDATE DATE,
MODIFY COLUMN ANNUALREVENUE DECIMAL(18, 2);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/SUPERMARKET_CONTACTS_COMPLETE.txt'
INTO TABLE supermarket_contacts
FIELDS TERMINATED BY ','
IGNORE 1 ROWS
(CUST_ID, COMPANY, ADDR1, ADDR2, ADDR3, ADDR4, COUNTRY, NAMEPREFIX, FIRSTNAME, SURNAME, TITLE, EMAIL);

use cdi_student2;

CREATE TABLE EMP_SALES_QTR (
    EMP_ID INT,
    EMP_FULL_NAME VARCHAR(255),
    REGION_ID INT,
    Q1_TOTAL DECIMAL(18, 4),
    Q2_TOTAL DECIMAL(18, 4),
    Q3_TOTAL DECIMAL(18, 4),
    Q4_TOTAL DECIMAL(18, 4)
);
CREATE TABLE QUARTERLY_SALES (
    EMP_ID VARCHAR(50) NOT NULL,
    EMP_NAME VARCHAR(255) NOT NULL,
    EMP_REGION VARCHAR(50) NOT NULL,
    Q1_SALES DECIMAL(10, 2) NOT NULL,
    Q2_SALES DECIMAL(10, 2) NOT NULL,
    Q3_SALES DECIMAL(10, 2) NOT NULL,
    Q4_SALES DECIMAL(10, 2) NOT NULL,
    YEARLY_TOTAL DECIMAL(10, 2)NOT NULL
);

CREATE TABLE TOTALAMOUNT (
    FULLNAME VARCHAR(255),
    ACCOUNTVALUE DECIMAL(18, 4)
);
CREATE TABLE WEEKLY_SALES_BY_STORE (
    STORE_ID INT,
    LOCATION VARCHAR(255),
    TRANSACTIONS INT,
    REVENUE DECIMAL(18, 4),
    AVG_REVENUE_PER_TRANS DECIMAL(18, 4)
);
CREATE TABLE YEARLY_EMP_SALES (
    EMP_ID INT,
    EMP_NAME VARCHAR(255),
    REGION_ID INT,
    YEARLY_SALES DECIMAL(18, 4)
);

use CDI_student2;
drop table employee_yearly_sales;